version: '2'
services:
    beethoven-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/Beethoven/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=Beethoven
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
